conditions: v1
sudo: required
dist: xenial
language: node_js
node_js:
  - "node"

addons:
  chrome: stable

services:
  - xvfb
cache:
  yarn: true
  directories:
    - node_modules

before_install:
  - export DISPLAY=:99.0

script:
  - yarn install

stages:
  - Release canary
  - Release
jobs:
  fast_finish: true
  include:
    # publish canary package if on master
    - stage: Release canary
      if: (branch = master) AND (type != pull_request)
      env: TRAVIS_MODE=releaseCanary
      deploy:
        provider: npm
        edge: true
        api_key: $NPM_TOKEN
        email: $NPM_EMAIL
        skip_cleanup: true
        tag: canary
        on:
          tags: false
          branch: master
