conditions: v1
sudo: required
dist: xenial
language: node_js
node_js:
  - "node"

addons:
  chrome: stable

services:
  - xvfb
cache:
  yarn: true
  directories:
    - node_modules

before_install:
  - export DISPLAY=:99.0

install:
  - yarn install

stages:
  - Check
  - Release

jobs:
  fast_finish: true
  include:
    # https://docs.travis-ci.com/user/build-stages/deploy-github-releases/
    - stage: Check
      name: "Check a new version"
      if: tag IS present
      deploy:
        - provider: script
          on:
            branch: master
            tags: true
          script: echo "master"
        - provider: script
          on:
            all_branches: true
            condition: $TRAVIS_BRANCH != master
            tags: true
          script: echo "side branch"
    - stage: Release
      name: "Releasing a new version"
      if: tag IS present
      script:
        - conventional-github-releaser -p angular -t $GH_NOTE_TOKEN
