conditions: v1
sudo: required
dist: xenial
language: node_js
node_js:
  - "node"

addons:
  chrome: stable

services:
  - xvfb
cache:
  yarn: true
  directories:
    - node_modules

before_install:
  - export DISPLAY=:99.0

script:
  - yarn install
  - git show-branch --no-name $TRAVIS_COMMIT

stages:
  - check
  - Release canary
  - Release
jobs:
  fast_finish: true
  include:
    # https://docs.travis-ci.com/user/build-stages/deploy-github-releases/
    - stage: Release
      name: "Releasing a new version"
      if: tag IS present
      deploy:
        - provider: script
          on:
            all_branches: true
            branch: master
            tags: true
          script: bash deploy.sh "test1" "$TRAVIS_BRANCH" "YES"
        - provider: script
          on:
            all_branches: true
            tags: true
          script: bash deploy.sh "test1" "$TRAVIS_BRANCH" "NO"
    - stage: Release canary
      name: "Release canary"
      if: (branch = master) AND (type != pull_request) AND commit_message !~ /^chore\(release\)/
      deploy:
        - provider: script
          on:
            tags: false
            branch: master
          script: bash deploy.sh "test3" "$TRAVIS_BRANCH" "YES"
    - stage: check
      name: "Check"
      script:
        - git show-branch --no-name $TRAVIS_COMMIT
