conditions: v1
sudo: required
dist: xenial
language: node_js
node_js:
  - "node"

addons:
  chrome: stable

services:
  - xvfb
cache:
  yarn: true
  directories:
    - node_modules

before_install:
  - export DISPLAY=:99.0
  - chmod +x ./travis.sh
  - chmod +x ./deploy.sh
  - chmod +x ./before_deploy.sh

script:
  - bash ./travis.sh

stages:
  - Prepare canary
  - Tests
  - Release canary
  - Release

jobs:
  fast_finish: true
  include:
    # https://docs.travis-ci.com/user/build-stages/deploy-github-releases/
    - if: (branch = master) AND (type != pull_request) AND commit_message !~ /^chore\(release\)/ AND commit_message !~ /^(chore).*(update dist)$/
      env: yuval=prepareCanary
    # publish canary package if on master
    - stage: Release
      if: (tag IS present)
      name: 'Release'
      env: TRAVIS_MODE=release
      deploy:
        - provider: script
          on:
            tags: true
            all_branches: true
          script: bash ./deploy.sh
    # https://docs.travis-ci.com/user/build-stages/deploy-github-releases/
    # publish canary package if on master
    - stage: Release canary
      if: (branch = master) AND (type != pull_request) AND commit_message !~ /^chore\(release\)/ AND commit_message !~ /^(chore).*(update dist)$/
      name: 'Release canary'
      env: TRAVIS_MODE=releaseCanary
      before_deploy:
        - provider: script
          on:
            all_branches: true
          script: bash ./before_deploy.sh
      deploy:
        - provider: script
          on:
            all_branches: true
          script: bash ./deploy.sh
    # Required tests
    - stage: Tests
      if: (branch = master) OR (tag IS present) OR (type = pull_request)
      name: "Running lint"
      env: TRAVIS_MODE=lint
