conditions: v1
sudo: required
dist: xenial
language: node_js
node_js:
  - "node"

addons:
  chrome: stable

services:
  - xvfb
cache:
  yarn: true
  directories:
    - node_modules

before_install:
  - export DISPLAY=:99.0

if: branch = master AND tag IS present
install:
  - yarn upgrade @playkit-js/playkit-js@canary

script:
  - yarn install

stages:
  - Check
  - Release

jobs:
  fast_finish: true
  include:
    # https://docs.travis-ci.com/user/build-stages/deploy-github-releases/
    - stages: Check
      name: "Check"
      if: (branch = master) OR (tag IS present) OR (type = pull_request)
      script:
        - cat package.json
    - stage: Release
      name: "Releasing a new version"
      if: tag IS present
      script:
        - conventional-github-releaser -p angular -t $GH_NOTE_TOKEN
