# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
    tags:
      - 'v*'
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Print node and yarn versions
        run: |
          node --version
          yarn --version
      - name: Install dependencies
        run: yarn install --check-files

      # extract branch name on pull request
      - name: Print branch name
        run: |
          git_hash=$(git rev-parse --short "$GITHUB_SHA")
          git_branch=${GITHUB_REF#refs/heads/}
          echo $git_hash
          echo $git_branch


      - name: Build
        run: echo "Build new version"

      - name: Run ESLint
        run: echo "yarn lint"
        env:
          CI: true

      - name: Run tests
        run: echo "yarn test"
        env:
          CI: true

      - name: Travis script
        run: |
          chmod +x ./travis.sh
          bash ./travis.sh

      - name: Before deploy
        run: |
          chmod +x ./before_deploy.sh
          bash ./before_deploy.sh

      - name: Deploy
        run: |
          chmod +x ./deploy.sh
          bash ./deploy.sh
